version: '1.0'
name: obsidian-rag
status: active
description: MCP server for semantic search over your Obsidian vault. Uses OpenAI embeddings by default (or Ollama for local processing) with ChromaDB for vector storage.
created: 2026-01-21
tags: []
_auto:
  git:
    is_repo: true
    remotes:
      origin: https://github.com/ernestkoe/obsidian-notes-rag.git
    current_branch: main
    commits_last_7_days: 0
    commits_last_30_days: 46
    days_since_last_commit: 8
  stats:
    total_size: 41172402
    code_size: 83168
    file_count: 44
    code_file_count: 17
  primary_language: Python
  project_type: Python
  last_scanned: 2026-01-21T18:23:52.666121+00:00
user:
  favorite: false
  archived: false
  notes: ''
  custom_fields: {}
